### ISSUE TITLE
libtomcrypt.pc contains DESTDIR in prefix

### ISSUE THREAD

**Issue by andreyv** [libtom/libtomcrypt#232] opened 2017-06-18 13:23 UTC
When building the library with `makefile.shared`, the generated `libtomcrypt.pc` contains `DESTDIR` as prefix.

`DESTDIR` normally denotes a staging root directory where software is installed and then archived. E.g., if the installation prefix was `/usr` and `DESTDIR` was `/tmp/package-root`, the full installation path would be `/tmp/package-root/usr`, and then a package would be created from `/tmp/package-root`, containing `usr/*` entries inside. With the current makefiles `DESTDIR` serves the role of the installation prefix instead and there is no separate way to actually specify a staging directory.

References:
https://www.gnu.org/prep/standards/html_node/DESTDIR.html
https://www.freebsd.org/doc/en/books/porters-handbook/porting-prefix.html

**Comment by sjaeckel** [comment] 2017-06-19 12:10
IIRC we had that discussion already once @rofl0r ... :-/
Fine like that?

**Comment by andreyv** [comment] 2017-06-19 20:50
Seems good.

**Comment by rofl0r** [comment] 2017-06-19 21:41
i added some comments in the commit.

**Comment by rofl0r** [comment] 2017-06-20 20:10
what you just committed doesn't look quite right...

**Comment by sjaeckel** [comment] 2017-06-22 10:47
fine like that?

**Comment by rofl0r** [comment] 2017-06-22 22:12
looks good, thanks! there's only a minor issue with double slashes; i commented in the commit.

**Comment by sjaeckel** [comment] 2017-06-23 05:59
btw there was still a real bug in `makefile_include.mk` ...

**Comment by rofl0r** [comment] 2017-06-23 14:17
great! looks like the issue is now a thing of the past <3

**Closed** 2017-06-27 18:05 UTC
