### ISSUE TITLE
16k+ errors building the library with nmake on windows

### ISSUE THREAD

**Issue by sebastianjkern** [libtom/libtomcrypt#482] opened 2019-04-24 22:04 UTC
### Description

I get over 16k errors when i build the makefile.msvc using nmake on windows. But most of them are just syntax errors like 

syntax error: missing '{' before '*'
syntax error: ';'
error C2085: 'pkcs_1_mgf1': not in formal parameter list

### Steps to Reproduce
I used the newest version (24 March 2019) and compiled it using nmake with MSVC 2017.

### Additional Information

I am just wondering if this is a problem with file encoding under Windows, because i compiled it on Ubuntu without any problems.

**Comment by karel-m** [comment] 2019-06-03 07:04
I confirm I can reproduce this behaviour.

**Comment by karel-m** [comment] 2019-06-03 07:26
@Maeusezaehnchen could you please try the latest develop branch?

**Comment by karel-m** [comment] 2019-06-03 07:29
It seems to fixed by https://github.com/libtom/libtomcrypt/pull/481

**Comment by sjaeckel** [comment] 2019-06-03 07:36
We should really get appveyor up and running

**Comment by sjaeckel** [comment] 2019-06-30 10:51
as it seems to be fixed by #481 I'm closing this, please reopen if the problem persists for you

**Closed as completed by sjaeckel** 2019-06-30 10:51 UTC
