### ISSUE TITLE
Importing RSA public key with help rsa_import()

### ISSUE THREAD

**Issue by anisyanka** [libtom/libtomcrypt#496] opened 2019-09-15 19:24 UTC
Hello. I work with libtomcrypt on armv7hl platform.

I have two c-arrays. `private_key_der` and `public_key_der`. One of them is data of private key, other is public key data.

I have done key-arrays with help this steps:

1. generated RSA key in *.pem format.
2. generated *.der (need for libtomcrypt) with help this [answer](https://stackoverflow.com/questions/31034781/how-do-i-use-libtomcrypt-to-import-an-rsa-public-key). 
3. done c-arrays from output.

I need to import public and private key for verifying and signature. 
That's why I use rsa_import() function from tomcrypt.
It's looks like:

`static rsa_key private_key;`
`static rsa_key public_key;`

`if ((err = rsa_import(private_key_der,` `sizeof(private_key_der),`
    `&private_key)) != CRYPT_OK) {`
    `EMSG("PRIVATE import failed: %d", err);`
`}`

`if ((err = rsa_import(public_key_der,` `sizeof(public_key_der),`
    `&public_key)) != CRYPT_OK) {`
    `EMSG("PUBLIC import failed: %d", err);`
`}`

Importing of private key is successful always, but I have trouble with public key. In public key case rsa_import() returns CRYPT_INVALID_PACKET. (0x07 error code) 
I have tried debugging libtocrypt and have learn that some error is happened in this code into rsa_import() function in libtomcrypt:

```
   /* not SSL public key, try to match against PKCS #1 standards */
   if ((err = der_decode_sequence_multi(in, inlen, 
                                  LTC_ASN1_INTEGER, 1UL, key->N, 
                                  LTC_ASN1_EOL,     0UL, NULL)) != CRYPT_OK) {
      goto LBL_ERR;
   }
```
It's strange.  
I have tried to use keys from libtomcrypt tests,  but I have got a same result. 
Could you tell me how can I import RSA public key?

**Comment by sjaeckel** [comment] 2019-09-16 07:36
This duplicates https://github.com/OP-TEE/optee_os/issues/3277

> Could you tell me how can I import RSA public key?

As you described (normally).

> Importing of private key is successful always, but I have trouble with public key.

> I have tried to use keys from libtomcrypt tests, but I have got a same result.

Two strange things:
1. that the import of the private key works
2. that the public keys of our internal tests don't work

As you're using it from op-tee I don't know how we can help further. I guess you missed some initialization or I don't know what.

I'm closing this as I'm pretty sure that it's not caused by an error in ltc. If you think differently feel free to re-open with new findings.

**Comment by anisyanka** [comment] 2019-09-16 08:01
I have found more old issue with same troubles. [
Libtomcrypt armv8 aarch64 troubles](https://github.com/libtom/libtomcrypt/issues/160#issuecomment-284131324). 
But I do not understand what should I do that to fix it. 
Some comments in the issue have old links.

> As you're using it from op-tee I don't know how we can help further. I guess you missed some initialization or I don't know what.

I have tried to run my example on just ARM-Linux plaform (not OP-TEE). And I have got a same result with public key.
It's seems to me, that the  point is in the platform, in particular ARM-based platforms in common with rsa_import(public).

**Comment by sjaeckel** [comment] 2019-09-16 08:02
Can you post the public key?

**Comment by anisyanka** [comment] 2019-09-16 08:07
```
const unsigned char rsa_public_key_der[] =
{
	0x30, 0x82, 0x01, 0x22, 0x30, 0x0d, 0x06, 0x09, 0x2a, 0x86, 0x48, 0x86,
	0xf7, 0x0d, 0x01, 0x01, 0x01, 0x05, 0x00, 0x03, 0x82, 0x01, 0x0f, 0x00,
	0x30, 0x82, 0x01, 0x0a, 0x02, 0x82, 0x01, 0x01, 0x00, 0xdf, 0xd5, 0xcb,
	0x86, 0x32, 0x07, 0x04, 0xe5, 0x27, 0x3d, 0xfa, 0xf0, 0x22, 0xa6, 0xef,
	0x8f, 0x3f, 0x7c, 0x4a, 0xd9, 0x60, 0x45, 0xc3, 0x6f, 0x5a, 0xc2, 0xe2,
	0x88, 0x42, 0x71, 0x09, 0xa8, 0xdf, 0xcd, 0x53, 0xf3, 0x8c, 0x06, 0xae,
	0xbb, 0xdc, 0x48, 0xba, 0x39, 0x0f, 0x19, 0x53, 0xa4, 0x1b, 0x22, 0xce,
	0xe8, 0xb6, 0x21, 0xfa, 0x20, 0x88, 0x36, 0x92, 0x4a, 0x1e, 0x98, 0xe2,
	0xde, 0xf9, 0xc7, 0xf4, 0xe4, 0xef, 0xa0, 0xa3, 0x60, 0x44, 0x9e, 0x88,
	0x0e, 0x6e, 0x51, 0x24, 0xf5, 0xb0, 0x52, 0xd7, 0xb3, 0x4e, 0xa8, 0x84,
	0xe8, 0x76, 0xe6, 0x3d, 0xc5, 0x60, 0x71, 0xc9, 0x3e, 0x71, 0x56, 0x7c,
	0x9c, 0xf5, 0x48, 0x88, 0xb0, 0x8f, 0x16, 0x41, 0xd2, 0x3c, 0xb0, 0x00,
	0x66, 0x34, 0x92, 0x77, 0xe5, 0x41, 0x36, 0x9e, 0x67, 0xf5, 0x83, 0x61,
	0xec, 0x89, 0x87, 0xdc, 0x87, 0x68, 0x64, 0x17, 0x12, 0x05, 0xcb, 0xb4,
	0xdb, 0x00, 0xa3, 0x46, 0x33, 0x91, 0xdd, 0xde, 0x22, 0x24, 0x59, 0x25,
	0x60, 0xc9, 0xf3, 0xe7, 0x8a, 0x81, 0xd2, 0xdf, 0x48, 0x63, 0x35, 0x2e,
	0xae, 0x9a, 0x56, 0xc0, 0x94, 0x30, 0xa2, 0x8e, 0xcc, 0xe0, 0x31, 0xf9,
	0xb5, 0xf4, 0xea, 0x53, 0x3b, 0x07, 0x93, 0xd3, 0x83, 0x6a, 0x14, 0x22,
	0x55, 0x2a, 0xfe, 0xc2, 0xcb, 0x87, 0x9c, 0xcd, 0xe5, 0x5b, 0x6c, 0x93,
	0xe3, 0x22, 0x55, 0xbd, 0x91, 0xe6, 0xc3, 0x5b, 0x4d, 0xfe, 0x1a, 0xa3,
	0x4b, 0x33, 0xf3, 0x29, 0xf4, 0xe5, 0xa3, 0x6f, 0x8b, 0x48, 0x59, 0xb4,
	0x98, 0x9b, 0xcd, 0xd0, 0xee, 0x94, 0x85, 0xcb, 0x24, 0x4e, 0xa6, 0x98,
	0x3e, 0x0b, 0x56, 0x48, 0x7b, 0x0b, 0xa6, 0x8b, 0x2d, 0xd6, 0x11, 0x5e,
	0x35, 0x43, 0xdc, 0xdd, 0xcd, 0x89, 0x98, 0x32, 0xcf, 0x63, 0xc8, 0x37,
	0x55, 0x02, 0x03, 0x01, 0x00, 0x01
};
```

**Comment by anisyanka** [comment] 2019-09-16 08:17
I have generated this key on x86_64 and hard coded it to my ARM application.
May be do I need to generate keys on ARM?

**Comment by sjaeckel** [comment] 2019-09-16 08:18
```c
int main(void)
{
   rsa_key k;
   int err;

   ltc_mp = ltm_desc;
   register_all_ciphers();
   register_all_hashes();
   register_all_prngs();

   if ((err = rsa_import(rsa_public_key_der, sizeof(rsa_public_key_der), &k)) != CRYPT_OK) {
      printf("rsa_import error: %s\n",error_to_string(err));
   } else {
      printf("k.N = 0x");
      mp_fwrite(k.N, 16, stdout);
      printf("\nk.e = 0x");
      mp_fwrite(k.e, 16, stdout);
      printf("\n");
   }
   return err;
}
```

results in

```
$ ./small 
k.N = 0xDFD5CB86320704E5273DFAF022A6EF8F3F7C4AD96045C36F5AC2E288427109A8DFCD53F38C06AEBBDC48BA390F1953A41B22CEE8B621FA208836924A1E98E2DEF9C7F4E4EFA0A360449E880E6E5124F5B052D7B34EA884E876E63DC56071C93E71567C9CF54888B08F1641D23CB00066349277E541369E67F58361EC8987DC876864171205CBB4DB00A3463391DDDE2224592560C9F3E78A81D2DF4863352EAE9A56C09430A28ECCE031F9B5F4EA533B0793D3836A1422552AFEC2CB879CCDE55B6C93E32255BD91E6C35B4DFE1AA34B33F329F4E5A36F8B4859B4989BCDD0EE9485CB244EA6983E0B56487B0BA68B2DD6115E3543DCDDCD899832CF63C83755
k.e = 0x10001
```

but that's on x86_64

> I have generated this key on x86_64 and hard code it to my ARM application.
> May be do I need to generate keys on ARM?

no

**Comment by anisyanka** [comment] 2019-09-16 13:06
May be do I have trouble with versions?
I use tomcrypt from [OP-TEE](https://github.com/OP-TEE/optee_os/tree/master/core/lib/libtomcrypt)  (therefore I have opened issue there).
Version from op-tee, seems, doesn't use tommath. Is it important?

I built tomcrypt and tommath from this repo for ARM and for X86 and then I compiled your example for both platforms and I have got same result.

```
x86 and arm:
k.N = 0xDFD5CB86320704E5273DFAF022A6EF8F3F7C4AD96045C36F5AC2E288427109A8DFCD53F38C06AEBBDC48BA390F1953A41B22CEE8B621FA208836924A1E98E2DEF9C7F4E4EFA0A360449E880E6E5124F5B052D7B34EA884E876E63DC56071C93E71567C9CF54888B08F1641D23CB00066349277E541369E67F58361EC8987DC876864171205CBB4DB00A3463391DDDE2224592560C9F3E78A81D2DF4863352EAE9A56C09430A28ECCE031F9B5F4EA533B0793D3836A1422552AFEC2CB879CCDE55B6C93E32255BD91E6C35B4DFE1AA34B33F329F4E5A36F8B4859B4989BCDD0EE9485CB244EA6983E0B56487B0BA68B2DD6115E3543DCDDCD899832CF63C83755
k.e = 0x10001
```
It seems that I really have problems with the OP-TEE tomcrypt.

**Comment by sjaeckel** [comment] 2019-09-16 14:05
I've just tried on `armv7l` (raspberry pi) and it gives the same result

**Closed as completed by sjaeckel** 2019-09-16 14:05 UTC

**Comment by sjaeckel** [comment] 2019-09-16 14:07
ah, I didn't see your latest comment

> It seems that I really have problems with the OP-TEE tomcrypt.

I think so too

**Comment by anisyanka** [comment] 2019-09-16 14:17
Thank you
